### PR TITLE
Add support of AutomationProperties to GetElementAttribute

### LINKED ISSUE #114: Make AutomationProperties accessible using GetAttribute

### PR DESCRIPTION
**Pull request by NickAb**
Fixes #114 

Usage example:
```py
element.get_attribute('AutomationIdProperty')
```

### CODE REVIEW

**Comment by NickAb** [comment]
Full list of automation properties can be found in [msdn article](https://msdn.microsoft.com/en-us/library/system.windows.automation.automationproperties(v=vs.110).aspx#Anchor_4)

Note that attribute name should end with `Property`, e.g. `AcceleratorKeyProperty`, `NameProperty`

**Comment by skyline-gleb** [comment]
может быть стоит сразу влить `WiniumElement.GetSetAttribute.cs` в `WiniumElement.cs` ?

**Comment by NickAb** [comment]
@skyline-gleb ping

**Comment by skyline-gleb** [comment]
Сборка успешна http://opensource-ci.2gis.ru/job/Winium.StoreApps-PRs/111/

**Pull request merged**
